server:
  port:

logging:
  level:
    com.neprozorro: INFO

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=neprozorro
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        order_by:
          default_null_ordering: last

openai:
  model: "gpt-3.5-turbo"
  temperature: 1.5
  api:
    url: "https://api.openai.com/v1/chat/completions"
    key: "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"