laptop:
  models: Acer, Alienware, Apple, ASUS, Aorus, Avita, Azom, BenQ, Chuwi, Clevo, Compaq, CyberPowerPC, Dell, Digital Storm, Dynabook, Fujitsu, Gateway, Gigabyte, Google, Haier, Hasee, HP, Huawei, iBUYPOWER, IBM, Intel, Jumper, Kenwood, Kogan, Laptops Direct, Lava, Lenovo, LG, Maingear, Maxdata, Mechanic, Medion, Microsoft, MSI, Nexoc, Nokia, Origin PC, Packard Bell, Panasonic, Pegatron, Philco, Pioneer Computers, Positivo, ProStar, Razer, Sager, Samsung, Schenker, Sharp, Shuttle, Sony, System76, Targa, TCL, Teclast, Tencent, Terra Mobile, Toshiba, TrekStor, Uniwill, VAIO, Velocity Micro, Vestel, Vizio, Walmart, Xiaomi, XOTIC PC, YuanDao, Zoostorm, 3K Computers, 3Q, Aftershock, Airis, AJP, Alldocube, Allview, Amoi, Aorus, Archos, Arctic, Arima, Artizlee, Astro, AsusPro, Atlas, Averatec, Avell, Aya, Azuma, Bangho,BBEN, Beko, BGH, Biostar, Blaupunkt, Bluechip, BossMonster, Brave, BTO, CCE, Centerm, CHUWI, Cinetix, Cizmo, Clamshell, Colorful, Compal, ConceptD, Coradir, Cube, CybertronPC, Dan, Datawind, Datalogic, Datamini, DBC, Decent, Devialet, Digitalnow, Durabook, ECS, Eee PC, Ekoore, Elephone, Elitegroup, Ematic Emdoor, Endless, Envy, Ergo, Eurocom, Everex, Exper, Falcon, FIC, Fizzbook, Fluo, Flybook, Founder, Fujitsu-Siemens, Fusion5, Gateway, Gdium, Gemini
server:
  port:

logging:
  level:
    com.neprozorro: INFO

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=neprozorro
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        order_by:
          default_null_ordering: last
