laptop:
  models: lenovo, hp, dell, apple, asus, microsoft, toshiba, sony, samsung, msi, lg, fujitsu, panasonic, huawei, razer, google, intel, gigabyte, alienware, xiaomi, vaio, nec, medion, sharp, gateway, ibm, compal, cyberpowerpc, eurocom, xotac, vizio, haier, positivo, jumper, chuwi, prestigio, everex, motion momputing, hasee, maxdata, aorus, teclast, malibal, system76, byond, tuxedo computers, nextbook, vinga, emdoor
server:
  port: 8080

logging:
  level:
    com.parsing: INFO

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=neprozorro
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        order_by:
          default_null_ordering: last
